import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { getServerSession } from "next-auth";
import "./globals.css";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { SessionProviderWrapper } from "@/components/session-provider";
import { SiteHeader } from "@/components/site-header";
import { authOptions } from "@/lib/auth";

const geistSans = Geist({
  variable: "--font-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Skedule: Modern Appointments",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <SessionProviderWrapper session={session}>
          <ThemeProvider>
            <SiteHeader />
            <div className="flex-1">{children}</div>
          </ThemeProvider>
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
